Software Managed Virtual Pointer
================================

This folder contains the implementation of a software-managed virtual
pointer that facilitates a pointer interface for SYCL buffers.
This virtual address
space is non-dereferenceable on the host, but accessors can be obtained
in the SYCL command groups.

This differs from the legacy_pointer interface in that a contiguous
virtual address space of size_t bits is created. 
When allocating a buffer using *SYCLMalloc*, a virtual address in the
range of 1 to 2<sup>64<sup> is returned. This is, in practise, a number
that identifies a certain SYCL buffer. 
The pointer can be offseted, so that positions inside a given buffer 
can be identified and passed around in higher-level functions.

[source,cpp]
--
// Create the Pointer Mapper structure
PointerMapper<> pMap;
// Create a SYCL buffer of 10 floats
float * a = static_cast<float *>(SYCLmalloc(10 * sizeof(float)), pMap);
// Create a SYCL buffer of 25 integers
int * b = static_cast<int *>(SYCLmalloc(25 * sizeof(int)), pMap);
// Create a pointer to the 5th element
float * c = a + 5; 
// Retrieve the buffer
assert(pMap.get_buffer(a) == pMap.get_buffer(c))
assert(pMap.get_offset(c) == 5)

// Invalid usage: no-dereference on the host
// float myVal = *c;
// Valid access on host: Use host-accessor
{
  auto syclAcc = pMap.get_buffer(a).get_access<access::mode::read, 
                                              access::target::host_buffer>();
  float myVal = syclAcc[0];
}

// Free the pointers
SYCLfree(a);
SYCLfree(b);
--



Developers looking for a simple replacement of malloc/free functions should
use the Legacy Pointer interface.
In situations where developers need complete addressing of the entire
device memory space, developers should use this software-managed 
virtual pointer.

Contents
--------

[source,bash]
--
.
├── CMakeLists.txt
├── include
│   ├── pointer_alias.hpp
│   └── virtual_ptr.hpp
├── README.adoc
└── tests
    ├── basic.cc
    ├── CMakeLists.txt
    ├── CMakeLists.txt.in
    └── offset.cc
--

Usage
-----

Include the _virtual_ptr_ header file in your program.
Replace your device malloc and free operations with *codeplay::SYCLmalloc*
and *codeplay::SYCLfree*.
These functions are not re-entrant, even thought the underlying SYCL 
buffer objects are thread-safe.

To retrieve the buffer from the virtual pointer, use the 
*codeplay::PointerMapper::get_buffer* function.
The offset can be retrieved using the
*codeplay::PointerMapper::get_offset* function.

See the tests for basic usage examples.
Note that the pointer is non-dereferenceable on the host, but host accessors
can be constructed once the buffer is retrieved.


Building tests
--------------

1. mkdir build
2. cd build
3. cmake ../ -DCOMPUTECPP_PACKAGE_ROOT_DIR=/path/to/computecpp/package/ -DCMAKE_MODULE_PATH=../../../cmake/Modules/
4. make


